# Generated by Django 2.2.16 on 2022-11-15 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_group_pub_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='pub_date',
        ),
    ]
