# Generated by Django 2.2.16 on 2022-11-17 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_follow'),
    ]

    operations = [
        migrations.AddField(
            model_name='follow',
            name='post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='followed', to='posts.Post', verbose_name='Пост'),
            preserve_default=False,
        ),
    ]
