# Generated by Django 2.2.16 on 2022-11-17 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_follow_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follow',
            name='post',
        ),
    ]
