# Generated by Django 2.2.16 on 2022-11-20 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_remove_follow_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follow',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата подписки'),
        ),
    ]
