# Generated by Django 3.2.16 on 2023-01-15 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0017_auto_20230115_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='like',
            field=models.IntegerField(default=0, verbose_name='Количество лайков'),
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
